[project]
name = "auto-install"
version = "3.0.1"
description = "自动安装主程序"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pyqt5-qt5<=5.15.2",
    "PyQt5==5.15.4",
    "PyQt5-sip==12.9.0",
    "pyautogui==0.9.53",
    "opencv-python==4.5.5.62",
    "psutil==5.9.1",
    "pywin32==303",
    "pywinauto==0.6.8",
    "wmi==1.5.1",
    "winrt==1.0.21033.1",
    "playsound==1.2.2",
]
